-- Domande frequenti: categorie e domande gestite dalla dashboard (Setup > Domande frequenti).
-- Le categorie collegate a un prodotto (product_slug) compaiono anche nella pagina di quel prodotto.
create table if not exists public.faq_categories (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,
  name         text not null,
  product_slug text,                                  -- es. adesivi_resinati: la categoria vale anche per quella pagina prodotto
  sort         int not null default 0,
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);
create table if not exists public.faq_items (
  id           uuid primary key default gen_random_uuid(),
  category_id  uuid not null references public.faq_categories(id) on delete cascade,
  q            text not null,
  a            text not null,
  sort         int not null default 0,
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists faq_items_cat_idx on public.faq_items (category_id, sort);
alter table public.faq_categories enable row level security;
alter table public.faq_items enable row level security;
drop policy if exists "faq cat: public read" on public.faq_categories;
create policy "faq cat: public read" on public.faq_categories for select using (active = true or public.is_staff());
drop policy if exists "faq cat: staff all" on public.faq_categories;
create policy "faq cat: staff all" on public.faq_categories for all using (public.is_staff()) with check (public.is_staff());
drop policy if exists "faq items: public read" on public.faq_items;
create policy "faq items: public read" on public.faq_items for select using (active = true or public.is_staff());
drop policy if exists "faq items: staff all" on public.faq_items;
create policy "faq items: staff all" on public.faq_items for all using (public.is_staff()) with check (public.is_staff());

-- contenuti di partenza: gli argomenti di aiuto del sito attuale
insert into public.faq_categories (slug, name, sort) values ('materiali', 'Materiali', 0) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Che differenza c''è tra vinile monomerico e polimerico?', 'Il vinile monomerico è più economico e adatto per applicazioni a breve-medio termine (2-3 anni). Il vinile polimerico è più resistente, flessibile e durevole (5-7 anni), ideale per superfici curve e applicazioni esterne prolungate.', 0 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='Che differenza c''è tra vinile monomerico e polimerico?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quale materiale è più adatto per uso esterno?', 'Per uso esterno consigliamo il vinile polimerico con laminazione protettiva. Resiste a pioggia, sole, gelo e raggi UV. Per la massima durata in condizioni estreme, gli adesivi resinati offrono una protezione ancora superiore grazie alla cupola di resina.', 1 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='Quale materiale è più adatto per uso esterno?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Il materiale adesivo è rimovibile o permanente?', 'I nostri adesivi utilizzano un collante permanente di alta qualità. Una volta applicati, aderiscono saldamente alla superficie. Possono essere rimossi con l''aiuto di un phon o di prodotti specifici, ma non sono pensati per essere riposizionati più volte.', 2 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='Il materiale adesivo è rimovibile o permanente?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Su quali superfici posso applicare gli adesivi?', 'Gli adesivi aderiscono su superfici lisce e pulite come vetro, metallo, plastica rigida, legno laccato e carrozzeria auto. Non sono adatti per superfici porose (muri grezzi, tessuti) o fortemente irregolari. La superficie deve essere pulita e asciutta per una perfetta adesione.', 3 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='Su quali superfici posso applicare gli adesivi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come devo preparare la superficie prima di applicare l''adesivo?', 'La superficie deve essere pulita, asciutta e priva di polvere o grasso. Consigliamo di pulirla con alcool isopropilico o un detergente sgrassante e attendere che sia completamente asciutta. Evita di toccare la superficie con le dita dopo la pulizia per non lasciare residui di unto.', 4 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='Come devo preparare la superficie prima di applicare l''adesivo?');
insert into public.faq_items (category_id, q, a, sort) select id, 'I materiali sono certificati e sicuri?', 'Sì, tutti i nostri materiali sono conformi alle normative europee e privi di sostanze nocive. I vinili utilizzati sono certificati per uso indoor e outdoor. Per applicazioni specifiche come il settore alimentare, offriamo materiali certificati per contatto indiretto con alimenti.', 5 from public.faq_categories where slug='materiali' and not exists (select 1 from public.faq_items i where i.q='I materiali sono certificati e sicuri?');
insert into public.faq_categories (slug, name, sort) values ('protezioni-e-finiture', 'Protezioni e finiture', 1) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Che differenza c''è tra laminazione lucida e opaca?', 'La laminazione lucida dona un aspetto brillante e vivace ai colori, ideale per grafiche fotografiche e colori accesi. La laminazione opaca offre un effetto più elegante e satinato, riduce i riflessi e conferisce un look professionale e moderno.', 0 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='Che differenza c''è tra laminazione lucida e opaca?');
insert into public.faq_items (category_id, q, a, sort) select id, 'La laminazione è necessaria?', 'La laminazione protettiva è fortemente consigliata perché protegge la stampa da graffi, raggi UV, acqua e usura quotidiana. Senza laminazione, i colori possono sbiadire più rapidamente e la stampa è più vulnerabile ai danni. Tutti i nostri prodotti includono la laminazione protettiva.', 1 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='La laminazione è necessaria?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cos''è la finitura in rilievo e come funziona?', 'La finitura in rilievo è un effetto tridimensionale che viene applicato su zone specifiche del design tramite verniciatura UV selettiva. Puoi scegliere tra effetto lucido o opaco. L''effetto rilievo dona un tocco tattile premium al tuo adesivo, evidenziando loghi, scritte o dettagli grafici.', 2 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='Cos''è la finitura in rilievo e come funziona?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cosa significa base di bianco nella stampa?', 'La base di bianco è uno strato di inchiostro bianco stampato sotto la grafica. Serve a rendere i colori più coprenti e vividi, specialmente su materiali trasparenti o per vetrofanie. Per adesivi su vinile bianco non è generalmente necessaria, ma è fondamentale per vetrofanie e materiali trasparenti.', 3 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='Cosa significa base di bianco nella stampa?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quale protezione scegliere per adesivi destinati ad ambienti umidi?', 'Per ambienti umidi come bagni, cucine o esterni esposti alla pioggia, consigliamo la laminazione lucida che offre una barriera impermeabile più efficace. Per una resistenza ancora maggiore, gli adesivi resinati con la cupola di resina poliuretanica garantiscono una protezione totale dall''acqua.', 4 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='Quale protezione scegliere per adesivi destinati ad ambienti umidi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'La laminazione cambia i colori della stampa?', 'La laminazione può influire leggermente sulla percezione dei colori. La laminazione lucida tende a rendere i colori più vivaci e saturi, mentre quella opaca li rende leggermente più morbidi e meno riflettenti. In entrambi i casi, la differenza è minima e il risultato è sempre professionale.', 5 from public.faq_categories where slug='protezioni-e-finiture' and not exists (select 1 from public.faq_items i where i.q='La laminazione cambia i colori della stampa?');
insert into public.faq_categories (slug, name, sort) values ('adesivi-personalizzati', 'Adesivi Personalizzati', 2) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Quali forme sono disponibili per gli adesivi personalizzati?', 'Offriamo adesivi personalizzati in cinque forme: rotondi, quadrati, rettangolari, ovali e sagomati. Con il taglio sagomato, l''adesivo segue esattamente il contorno del tuo design, per un risultato professionale e senza bordi bianchi.', 0 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='Quali forme sono disponibili per gli adesivi personalizzati?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Qual è la dimensione minima e massima degli adesivi?', 'Le dimensioni variano in base alla forma scelta. In generale, la dimensione minima è di circa 10mm e la massima arriva fino a 300mm o oltre. Nel configuratore online troverai tutte le dimensioni disponibili per ciascuna forma.', 1 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='Qual è la dimensione minima e massima degli adesivi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso ordinare quantità diverse per lo stesso design?', 'Ogni configurazione nel carrello corrisponde a un prodotto specifico con le sue impostazioni (forma, dimensione, materiale, quantità). Se hai bisogno dello stesso design in quantità diverse, puoi aggiungerlo più volte al carrello con configurazioni diverse.', 2 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='Posso ordinare quantità diverse per lo stesso design?');
insert into public.faq_items (category_id, q, a, sort) select id, 'In che formato devo inviare il file grafico?', 'Accettiamo file in formato PDF, AI, EPS, SVG, PNG, JPG, JPEG e TIFF. Per il miglior risultato, consigliamo file vettoriali (PDF, AI, EPS, SVG) con colori in CMYK. Il peso massimo per file è 25MB.', 3 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='In che formato devo inviare il file grafico?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come funziona il taglio sagomato?', 'Il taglio sagomato segue il contorno esatto del tuo design grazie a una macchina da taglio di precisione. L''adesivo risultante non ha bordi bianchi né forme standard: la sua forma ricalca perfettamente la tua grafica. È la scelta ideale per loghi, mascotte e design con forme irregolari.', 4 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='Come funziona il taglio sagomato?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso richiedere un campione prima di ordinare una grande quantità?', 'Sì, puoi aggiungere un campione al carrello per testare materiale, colori e dimensioni prima di un ordine importante. Se lo aggiungi insieme ad altri prodotti, il campione è gratuito. Se lo ordini da solo, ha un costo di €10.', 5 from public.faq_categories where slug='adesivi-personalizzati' and not exists (select 1 from public.faq_items i where i.q='Posso richiedere un campione prima di ordinare una grande quantità?');
insert into public.faq_categories (slug, name, sort) values ('adesivi-resinati', 'Adesivi Resinati', 3) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Perché gli adesivi resinati costano di più rispetto agli altri?', 'Il costo maggiore è dovuto al processo di resinatura, che richiede l''applicazione manuale di resina poliuretanica bicomponente su ogni singolo adesivo tramite macchine CNC. Il risultato è un prodotto premium con effetto 3D, resistenza superiore e una durata che può raggiungere 7-10 anni.', 0 from public.faq_categories where slug='adesivi-resinati' and not exists (select 1 from public.faq_items i where i.q='Perché gli adesivi resinati costano di più rispetto agli altri?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso avere adesivi resinati con angoli vivi?', 'No, gli adesivi resinati necessitano di angoli arrotondati per garantire una distribuzione uniforme della resina. Con angoli vivi, la resina non si distribuirebbe correttamente e il risultato sarebbe imperfetto. Per questo motivo le forme disponibili prevedono sempre un raggio minimo sugli angoli.', 1 from public.faq_categories where slug='adesivi-resinati' and not exists (select 1 from public.faq_items i where i.q='Posso avere adesivi resinati con angoli vivi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Gli adesivi resinati sono adatti per applicazioni su auto e moto?', 'Assolutamente sì. La resina poliuretanica è estremamente resistente agli agenti atmosferici, ai lavaggi auto e alle vibrazioni. Gli adesivi resinati sono tra i più utilizzati nel settore automotive per loghi, badge e personalizzazioni su carrozzeria, cerchioni e caschi.', 2 from public.faq_categories where slug='adesivi-resinati' and not exists (select 1 from public.faq_items i where i.q='Gli adesivi resinati sono adatti per applicazioni su auto e moto?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quanto tempo serve per la produzione di adesivi resinati?', 'Gli adesivi resinati richiedono tempi di produzione leggermente più lunghi rispetto agli adesivi standard, a causa del processo di resinatura e dei tempi di indurimento della resina. In media i tempi di produzione sono di 5-7 giorni lavorativi dall''approvazione della prova di stampa.', 3 from public.faq_categories where slug='adesivi-resinati' and not exists (select 1 from public.faq_items i where i.q='Quanto tempo serve per la produzione di adesivi resinati?');
insert into public.faq_items (category_id, q, a, sort) select id, 'La resina ingiallisce nel tempo?', 'No, la resina poliuretanica che utilizziamo è di alta qualità e formulata per non ingiallire. Mantiene la sua trasparenza e brillantezza anche dopo anni di esposizione a raggi UV e agenti atmosferici. È uno dei principali vantaggi della resina poliuretanica rispetto ad altri tipi di resina.', 4 from public.faq_categories where slug='adesivi-resinati' and not exists (select 1 from public.faq_items i where i.q='La resina ingiallisce nel tempo?');
insert into public.faq_categories (slug, name, sort) values ('adesivi-in-rilievo', 'Adesivi in Rilievo', 4) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Qual è la differenza tra adesivi in rilievo e adesivi resinati?', 'Gli adesivi in rilievo hanno un effetto tridimensionale ottenuto tramite verniciatura UV selettiva su zone specifiche del design. Gli adesivi resinati hanno invece una cupola di resina trasparente che ricopre l''intera superficie. Il rilievo è più sottile e selettivo, la resina è più spessa e copre tutto.', 0 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='Qual è la differenza tra adesivi in rilievo e adesivi resinati?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso scegliere quali parti del design avranno il rilievo?', 'Sì, il rilievo viene applicato in modo selettivo. Puoi indicarci quali elementi del tuo design vuoi mettere in rilievo: loghi, testi, bordi o dettagli specifici. Il contrasto tra le zone piatte e quelle in rilievo crea un effetto visivo e tattile molto d''impatto.', 1 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='Posso scegliere quali parti del design avranno il rilievo?');
insert into public.faq_items (category_id, q, a, sort) select id, 'L''effetto rilievo si rovina nel tempo?', 'No, l''effetto rilievo è molto resistente grazie alla verniciatura UV che viene indurita con luce ultravioletta. Combinato con la laminazione protettiva, mantiene la sua consistenza e il suo aspetto per anni, anche in condizioni di uso intenso.', 2 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='L''effetto rilievo si rovina nel tempo?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Gli adesivi in rilievo sono adatti per uso esterno?', 'Sì, gli adesivi in rilievo sono perfettamente adatti per uso esterno. La verniciatura UV che crea l''effetto rilievo è resistente agli agenti atmosferici, e la laminazione protettiva aggiuntiva garantisce una durata di diversi anni anche esposti a pioggia, sole e gelo.', 3 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='Gli adesivi in rilievo sono adatti per uso esterno?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso avere il rilievo sia lucido che opaco sullo stesso adesivo?', 'Attualmente offriamo la finitura in rilievo in una sola variante per adesivo: o tutta lucida o tutta opaca. Non è possibile combinare rilievo lucido e opaco sullo stesso pezzo. Puoi però ordinare lo stesso design in due versioni separate, una con rilievo lucido e una con opaco.', 4 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='Posso avere il rilievo sia lucido che opaco sullo stesso adesivo?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Il rilievo si sente al tatto?', 'Sì, l''effetto rilievo è percepibile al tatto. Si crea uno spessore leggero ma evidente nelle zone trattate, che dona una sensazione premium e tridimensionale. Questo effetto tattile è uno dei principali punti di forza degli adesivi in rilievo, ideale per biglietti da visita, packaging di lusso e branding.', 5 from public.faq_categories where slug='adesivi-in-rilievo' and not exists (select 1 from public.faq_items i where i.q='Il rilievo si sente al tatto?');
insert into public.faq_categories (slug, name, sort) values ('etichette', 'Etichette', 5) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Come sono organizzate le etichette sui fogli?', 'Le etichette vengono disposte su fogli ottimizzando lo spazio, con pre-taglio (kiss-cut) che permette di staccarle facilmente una alla volta dal foglio di supporto. Ogni foglio è progettato per essere comodo da usare, sia per applicazione manuale che per piccole produzioni.', 0 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Come sono organizzate le etichette sui fogli?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Le etichette sono resistenti ad acqua e olio?', 'Sì, le nostre etichette sono stampate su vinile con laminazione protettiva che le rende resistenti ad acqua, olio, cibo e uso quotidiano. Sono ideali per prodotti cosmetici, alimentari, bevande e qualsiasi applicazione che richiede resistenza ai liquidi.', 1 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Le etichette sono resistenti ad acqua e olio?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso usare le etichette per i miei prodotti da vendere?', 'Certamente. Le nostre etichette sono perfette per branding di prodotti: bottiglie, barattoli, scatole, cosmetici, candele e molto altro. La qualità di stampa professionale e la resistenza dei materiali garantiscono un aspetto premium per i tuoi prodotti.', 2 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Posso usare le etichette per i miei prodotti da vendere?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quante etichette ci sono in ogni foglio?', 'Il numero di etichette per foglio dipende dalla dimensione scelta. Nel configuratore vedrai automaticamente quanti pezzi contiene ogni foglio in base alle dimensioni selezionate. Più piccole sono le etichette, più ne entrano per foglio.', 3 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Quante etichette ci sono in ogni foglio?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso scegliere la disposizione delle etichette sul foglio?', 'Il nostro team ottimizza automaticamente la disposizione per garantire il massimo numero di etichette per foglio. Se hai esigenze particolari sulla disposizione, puoi indicarlo nelle note dell''ordine o contattarci e faremo il possibile per accontentarti.', 4 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Posso scegliere la disposizione delle etichette sul foglio?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Le etichette sono adatte per bottiglie e barattoli curvi?', 'Sì, le nostre etichette sono realizzate in vinile flessibile che si adatta bene a superfici leggermente curve come bottiglie e barattoli. Per curve molto accentuate, consigliamo dimensioni contenute per evitare grinze. Il materiale polimerico offre la migliore flessibilità per queste applicazioni.', 5 from public.faq_categories where slug='etichette' and not exists (select 1 from public.faq_items i where i.q='Le etichette sono adatte per bottiglie e barattoli curvi?');
insert into public.faq_categories (slug, name, sort) values ('vetrofanie', 'Vetrofanie', 6) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Qual è la differenza tra applicazione interna ed esterna?', 'L''applicazione interna prevede che la vetrofania venga incollata all''interno del vetro e letta dall''esterno (stampa speculare). L''applicazione esterna si incolla direttamente sulla superficie esterna del vetro. L''applicazione interna è consigliata perché protegge la stampa dagli agenti atmosferici.', 0 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Qual è la differenza tra applicazione interna ed esterna?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Le vetrofanie bloccano completamente la luce?', 'Le vetrofanie standard coprono la parte stampata ma non bloccano completamente la luce. Le zone con colori chiari possono lasciare filtrare un po'' di luminosità. Per un effetto coprente totale, la base di bianco garantisce opacità completa nelle zone stampate.', 1 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Le vetrofanie bloccano completamente la luce?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso applicare le vetrofanie su plexiglass o superfici curve?', 'Le vetrofanie si applicano perfettamente su plexiglass e superfici trasparenti lisce. Per superfici leggermente curve funzionano bene, ma per curvature accentuate consigliamo dimensioni più piccole per evitare grinze. Non sono adatte per superfici opache o porose.', 2 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Posso applicare le vetrofanie su plexiglass o superfici curve?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come rimuovo una vetrofania senza danneggiare il vetro?', 'Le nostre vetrofanie si rimuovono facilmente sollevando un angolo e tirando lentamente. Se l''adesivo è molto tenace, puoi usare un phon per scaldare leggermente la superficie e facilitare la rimozione. Eventuali residui si puliscono con un detergente per vetri.', 3 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Come rimuovo una vetrofania senza danneggiare il vetro?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Le vetrofanie sono adatte per vetrine di negozi?', 'Assolutamente sì, le vetrofanie sono uno dei prodotti più richiesti per vetrine commerciali. Sono perfette per comunicare promozioni, orari, loghi e decorazioni. L''applicazione dall''interno protegge la stampa e permette di mantenere la vetrina pulita dall''esterno senza rischiare di rovinare la grafica.', 4 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Le vetrofanie sono adatte per vetrine di negozi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso ordinare vetrofanie con stampa fronte e retro?', 'Le vetrofanie vengono stampate su un solo lato con stampa speculare per applicazione dall''interno, oppure stampa normale per applicazione dall''esterno. Non è possibile stampare fronte e retro sullo stesso supporto, ma puoi ordinare due vetrofanie separate da applicare su entrambi i lati del vetro.', 5 from public.faq_categories where slug='vetrofanie' and not exists (select 1 from public.faq_items i where i.q='Posso ordinare vetrofanie con stampa fronte e retro?');
insert into public.faq_categories (slug, name, sort) values ('fogli-adesivi', 'Fogli Adesivi', 7) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Cosa sono i fogli adesivi e a cosa servono?', 'I fogli adesivi sono fogli con più adesivi disposti insieme, ognuno con il proprio mezzo taglio (kiss-cut). Sono perfetti per creare set, collezioni, kit promozionali o per chi ha bisogno di più grafiche diverse sullo stesso supporto. Ogni adesivo si stacca facilmente dal foglio.', 0 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='Cosa sono i fogli adesivi e a cosa servono?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso inserire grafiche diverse sullo stesso foglio?', 'Sì, puoi inserire quanti adesivi diversi vuoi sullo stesso foglio, anche con grafiche e forme differenti tra loro. Puoi combinare adesivi tondi, quadrati, rettangolari e sagomati sullo stesso foglio. Il layout viene ottimizzato per sfruttare al meglio lo spazio.', 1 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='Posso inserire grafiche diverse sullo stesso foglio?');
insert into public.faq_items (category_id, q, a, sort) select id, 'I fogli adesivi sono disponibili in verticale e orizzontale?', 'Sì, offriamo fogli adesivi in formato verticale, orizzontale e sagomato. Il formato sagomato permette di avere il foglio stesso tagliato su una forma personalizzata, non solo i singoli adesivi al suo interno.', 2 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='I fogli adesivi sono disponibili in verticale e orizzontale?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come funziona il taglio sui fogli adesivi?', 'Ogni adesivo sul foglio ha un mezzo taglio (kiss-cut) che incide solo il vinile senza tagliare il foglio di supporto. In questo modo puoi staccare ogni singolo adesivo facilmente, mantenendo il foglio intatto come base. È la soluzione ideale per packaging e distribuzione.', 3 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='Come funziona il taglio sui fogli adesivi?');
insert into public.faq_items (category_id, q, a, sort) select id, 'I fogli adesivi sono adatti come gadget promozionali?', 'Sì, i fogli adesivi sono perfetti come gadget promozionali, merchandising e omaggi. Puoi creare set tematici con il tuo brand, inserire più soggetti diversi sullo stesso foglio e distribuirli a eventi, fiere o come inserti negli ordini. Il formato foglio è pratico e ha un grande impatto visivo.', 4 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='I fogli adesivi sono adatti come gadget promozionali?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Qual è la dimensione massima di un foglio adesivo?', 'Le dimensioni dei fogli variano in base al formato scelto (verticale, orizzontale o sagomato). Nel configuratore puoi selezionare tra le dimensioni disponibili. Per esigenze fuori standard o dimensioni particolarmente grandi, contatta il servizio clienti per valutare la fattibilità.', 5 from public.faq_categories where slug='fogli-adesivi' and not exists (select 1 from public.faq_items i where i.q='Qual è la dimensione massima di un foglio adesivo?');
insert into public.faq_categories (slug, name, sort) values ('ordini-e-spedizioni', 'Ordini e spedizioni', 8) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Quali sono i tempi di produzione e consegna?', 'I tempi di produzione standard sono di 3-5 giorni lavorativi dalla approvazione della prova di stampa. La spedizione standard impiega ulteriori 2-4 giorni lavorativi. È disponibile anche la spedizione express per consegne più rapide con un supplemento del 30%.', 0 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Quali sono i tempi di produzione e consegna?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come posso tracciare il mio ordine?', 'Riceverai un''email con il codice di tracciamento non appena l''ordine viene spedito. Puoi monitorare lo stato della spedizione in tempo reale dalla sezione "I miei ordini" del tuo account, dove troverai il link diretto al tracking del corriere.', 1 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Come posso tracciare il mio ordine?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cosa succede dopo che effettuo un ordine?', 'Dopo l''ordine riceverai un''email di conferma. Il nostro team preparerà una prova di stampa digitale che ti verrà inviata via email per approvazione. Una volta approvata la prova e confermato il pagamento, l''ordine entra in produzione.', 2 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Cosa succede dopo che effettuo un ordine?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cos''è la prova di stampa e come funziona?', 'La prova di stampa è un''anteprima digitale del tuo adesivo nelle dimensioni reali. Ti verrà inviata via email con un link per approvarla o richiedere modifiche. Il pagamento viene elaborato automaticamente al momento dell''approvazione. Se richiedi modifiche, riceverai una nuova prova aggiornata.', 3 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Cos''è la prova di stampa e come funziona?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Con quali corrieri spedite?', 'Ci affidiamo ai principali corrieri nazionali per garantire consegne rapide e sicure in tutta Italia. Il corriere viene assegnato in base alla zona di destinazione e alla tipologia di spedizione scelta (standard o express).', 4 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Con quali corrieri spedite?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cosa succede se non sono a casa al momento della consegna?', 'Il corriere lascerà un avviso di passaggio e tenterà una seconda consegna il giorno lavorativo successivo. In alternativa, potrai contattare il corriere tramite il link di tracking ricevuto via email per riprogrammare la consegna o ritirare il pacco presso il punto di ritiro più vicino.', 5 from public.faq_categories where slug='ordini-e-spedizioni' and not exists (select 1 from public.faq_items i where i.q='Cosa succede se non sono a casa al momento della consegna?');
insert into public.faq_categories (slug, name, sort) values ('resi-e-rimborsi', 'Resi e rimborsi', 9) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso restituire un prodotto personalizzato?', 'I prodotti personalizzati possono essere restituiti solo in caso di difetti di produzione o errori da parte nostra. Trattandosi di articoli realizzati su misura, non è possibile il reso per ripensamento. Accettiamo reclami entro 14 giorni dalla consegna con documentazione fotografica del difetto.', 0 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Posso restituire un prodotto personalizzato?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come funziona il processo di rimborso?', 'Una volta verificato e approvato il reclamo, il rimborso viene elaborato entro 3-5 giorni lavorativi sullo stesso metodo di pagamento utilizzato per l''acquisto. Per pagamenti con carta di credito, il rimborso potrebbe richiedere ulteriori giorni per apparire sull''estratto conto.', 1 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Come funziona il processo di rimborso?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Cosa faccio se il prodotto arriva danneggiato?', 'Se il prodotto arriva danneggiato durante il trasporto, contattaci entro 48 ore dalla consegna inviando foto del pacco e del prodotto danneggiato. Provvederemo alla rispedizione gratuita o al rimborso completo a seconda della tua preferenza.', 2 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Cosa faccio se il prodotto arriva danneggiato?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Se la prova di stampa non mi piace, posso annullare l''ordine?', 'Sì, finché non approvi la prova di stampa puoi richiedere modifiche senza costi aggiuntivi. Se dopo le revisioni non sei soddisfatto, contatta il servizio clienti per discutere le opzioni disponibili. Il pagamento viene elaborato solo al momento dell''approvazione della prova.', 3 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Se la prova di stampa non mi piace, posso annullare l''ordine?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quante revisioni della prova di stampa posso richiedere?', 'Non c''è un limite fisso al numero di revisioni. Puoi richiedere le modifiche necessarie finché la prova non ti soddisfa pienamente. Il nostro obiettivo è che tu sia completamente soddisfatto del risultato prima di procedere con la stampa.', 4 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Quante revisioni della prova di stampa posso richiedere?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso richiedere la fattura per il mio ordine?', 'Sì, durante il checkout puoi inserire i dati di fatturazione (ragione sociale, partita IVA, codice SDI). La fattura verrà emessa automaticamente e inviata all''indirizzo email indicato. Se hai bisogno di una fattura per un ordine già effettuato, contatta il servizio clienti.', 5 from public.faq_categories where slug='resi-e-rimborsi' and not exists (select 1 from public.faq_items i where i.q='Posso richiedere la fattura per il mio ordine?');
insert into public.faq_categories (slug, name, sort) values ('domande-generali', 'Domande generali', 10) on conflict (slug) do nothing;
insert into public.faq_items (category_id, q, a, sort) select id, 'Offrite sconti per grandi quantità?', 'Sì, il nostro sistema calcola automaticamente sconti progressivi in base alla quantità ordinata. Più adesivi ordini, più basso sarà il prezzo unitario. Per quantità molto elevate o esigenze particolari, contattaci per un preventivo personalizzato.', 0 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Offrite sconti per grandi quantità?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso ordinare dei campioni prima di fare un ordine grande?', 'Sì, offriamo la possibilità di ordinare campioni. Se aggiungi un campione insieme ad altri prodotti nel carrello, il campione è gratuito. Se ordini solo il campione, il costo è di €10. È il modo migliore per verificare la qualità prima di un ordine importante.', 1 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Posso ordinare dei campioni prima di fare un ordine grande?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Quali metodi di pagamento accettate?', 'Accettiamo pagamenti con carta di credito/debito (Visa, Mastercard, American Express) tramite Stripe e PayPal. Il pagamento con carta viene elaborato in modo sicuro al momento dell''approvazione della prova di stampa.', 2 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Quali metodi di pagamento accettate?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Posso riordinare lo stesso prodotto senza riconfigurarlo?', 'Sì, nella sezione "Riordini" del tuo account trovi lo storico degli ordini precedenti con la possibilità di riordinare rapidamente lo stesso prodotto con le stesse specifiche, risparmiando tempo nella configurazione.', 3 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Posso riordinare lo stesso prodotto senza riconfigurarlo?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Devo creare un account per ordinare?', 'No, puoi effettuare ordini anche come ospite senza creare un account. Tuttavia, registrandoti avrai accesso allo storico ordini, al tracciamento delle spedizioni, ai riordini rapidi e alla gestione dei tuoi indirizzi e metodi di pagamento salvati.', 4 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Devo creare un account per ordinare?');
insert into public.faq_items (category_id, q, a, sort) select id, 'Come posso contattare il servizio clienti?', 'Puoi contattarci tramite il form nella sezione "Mandaci un''email" di questa pagina. Il nostro team risponde generalmente entro 24 ore lavorative. Per richieste urgenti, indica nell''oggetto la parola "URGENTE" e daremo priorità alla tua richiesta.', 5 from public.faq_categories where slug='domande-generali' and not exists (select 1 from public.faq_items i where i.q='Come posso contattare il servizio clienti?');
update public.faq_categories set product_slug='adesivi_personalizzati' where slug='adesivi-personalizzati' and product_slug is null;
update public.faq_categories set product_slug='adesivi_resinati' where slug='adesivi-resinati' and product_slug is null;
update public.faq_categories set product_slug='adesivi_rilievo' where slug='adesivi-in-rilievo' and product_slug is null;
update public.faq_categories set product_slug='etichette' where slug='etichette' and product_slug is null;
update public.faq_categories set product_slug='vetrofanie' where slug='vetrofanie' and product_slug is null;
update public.faq_categories set product_slug='fogli_adesivi' where slug='fogli-adesivi' and product_slug is null;
